#!/bin/sh
# live-build configuration for kisok-os.
# This script is run by `lb config` and defines how the bootable ISO is built.
set -e

lb config noauto \
	--mode debian \
	--distribution bookworm \
	--architecture amd64 \
	--archive-areas "main contrib non-free non-free-firmware" \
	--binary-images iso-hybrid \
	--debian-installer none \
	--mirror-bootstrap "http://deb.debian.org/debian/" \
	--mirror-chroot "http://deb.debian.org/debian/" \
	--mirror-chroot-security "http://security.debian.org/debian-security/" \
	--mirror-binary "http://deb.debian.org/debian/" \
	--mirror-binary-security "http://security.debian.org/debian-security/" \
	--apt-options "--yes" \
	--iso-application "kisok-os" \
	--iso-volume "kisok-os" \
	--memtest none \
	--bootappend-live "boot=live components quiet splash hostname=kisok-os" \
	"${@}"
